services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=warning
      - CONFIG=${DDNS_UPDATER_CONFIG}

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./app/static/:/static/
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

  app:
    build: app
    container_name: app
    restart: unless-stopped
    ports:
      - "8080:8080"
    command: uv run waitress-serve main:app

  src:
    build: src
    container_name: src
    restart: unless-stopped
    command: uv run uvicorn api:app --host 0.0.0.0 --workers 4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
