services:
  ddns-updater:
    image: qmcgaw/ddns-updater
    container_name: ddns-updater
    restart: unless-stopped
    volumes:
      - ./ddns-updater-data:/updater/data
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=warning

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./caddy-conf:/etc/caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"

  flask:
    build: flask
    container_name: flask
    restart: unless-stopped
    ports:
      - "8050:8050"
    command: gunicorn -w 10 -t 60 -b 0.0.0.0:8050 app.app:app
